services:
  # Backend Service
  - type: web
    name: agrimind-backend
    env: python
    region: oregon
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    
  # Frontend Service
  - type: web
    name: agrimind-frontend
    env: python
    region: oregon
    rootDir: frontend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run Home.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: BACKEND_URL
        fromService:
          type: web
          name: agrimind-backend
          envVarKey: RENDER_EXTERNAL_URL
